<?php

/**
 * SeoSuite
 *
 * Copyright 2019 by Sterc <modx@sterc.com>
 */

$_lang['seosuite.suggestions']                           = 'Suggestions';
$_lang['seosuite.suggestions_desc']                      = 'View and manage all URL suggestions generated by the AI system. You can create redirects from these suggestions or delete them.';
$_lang['seosuite.urls_view_suggestions']                 = 'View Suggestions';
$_lang['seosuite.label_url_score']                       = 'Score';
$_lang['seosuite.label_url']                             = 'URL';
$_lang['seosuite.label_url_createdon']                   = 'Created On';
$_lang['seosuite.create_redirects_selected']             = 'Create Redirects for Selected';
$_lang['seosuite.create_redirects_all']                  = 'Create Redirects for All';
$_lang['seosuite.create_redirects']                      = 'Create Redirects';
$_lang['seosuite.create_redirects_confirm']              = 'Are you sure you want to create redirects for the selected suggestions?';
$_lang['seosuite.create_redirect']                       = 'Create Redirect';
$_lang['seosuite.load_more_suggestions']                 = 'Load More Suggestions';
$_lang['seosuite.suggestions_loaded']                    = 'All Suggestions Loaded';
$_lang['seosuite.delete_selected']                       = 'Delete Selected';
$_lang['seosuite.suggestion_delete']                     = 'Delete Suggestion';
$_lang['seosuite.suggestion_delete_confirm']             = 'Are you sure you want to delete this suggestion?';
$_lang['seosuite.suggestions_delete']                    = 'Delete Suggestions';
$_lang['seosuite.suggestions_delete_confirm']            = 'Are you sure you want to delete the selected suggestions?';
$_lang['seosuite.suggestions_deleted']                   = 'Successfully deleted [[+count]] suggestions.';
$_lang['seosuite.error_no_suggestions']                  = 'No suggestions found.';
$_lang['seosuite.error_invalid_suggestions']             = 'Invalid suggestions format.';
$_lang['seosuite.error_no_suggestions_selected']         = 'No suggestions selected.';
$_lang['seosuite.error_no_url']                          = 'No URL provided.';
$_lang['seosuite.error_url_not_found']                   = 'URL not found.';
$_lang['seosuite.redirects_created']                     = 'Created [[+created]] redirects out of [[+total]] suggestions. [[+existing]] redirects already existed.';
$_lang['seosuite.ai_suggestions_generated']              = 'Generated suggestions for [[+total]] URLs: [[+success]] successful, [[+existing]] already had suggestions, [[+no_match]] had no matches, [[+error_page]] were error pages, [[+homepage_fallback]] redirected to homepage. Created [[+redirects]] redirects.';

// New strings for the Generate Suggestions functionality
$_lang['seosuite.urls_generate_suggestions']             = 'Generate Suggestions';
$_lang['seosuite.urls_generate_suggestions_selected']    = 'Generate AI Suggestions ';
$_lang['seosuite.urls_generate_suggestions_selected_confirm'] = 'Are you sure you want to generate suggestions for the selected URLs?';
$_lang['seosuite.urls_generate_suggestions_filtered']    = 'Generate Suggestions for Filtered URLs';
$_lang['seosuite.urls_generate_suggestions_filtered_confirm'] = 'Are you sure you want to generate suggestions for all URLs in the current view?';
$_lang['seosuite.ai_error_no_urls_selected']             = 'No URLs selected. Please select at least one URL.';

// Edit suggestion strings
$_lang['seosuite.suggestion_edit']                       = 'Edit Suggestion';
$_lang['seosuite.suggestion_edit_desc']                  = 'Edit the suggestion for this URL.';
$_lang['seosuite.label_suggestion_resource_id']          = 'Resource ID';
$_lang['seosuite.label_suggestion_resource_id_desc']     = 'The ID of the resource to suggest as a redirect target.';
$_lang['seosuite.label_suggestion_score']                = 'Score';
$_lang['seosuite.label_suggestion_score_desc']           = 'The score of this suggestion (0-100). Higher scores indicate better matches.';
$_lang['seosuite.error_suggestion_resource_id_ns']       = 'Resource ID is required.';
$_lang['seosuite.error_suggestion_score_invalid']        = 'Score must be a number between 0 and 100.';
$_lang['seosuite.suggestion_update_success']             = 'Suggestion updated successfully.';
